/* eslint-disable @typescript-eslint/no-require-imports */
const test = require('node:test');
const assert = require('node:assert/strict');

const {
  AUTOMATION_BRANCH_PREFIXES,
  inferWorkflowFromBranch,
  lintPrBody,
  lintAutomationPrs,
} = require('../lint-automation-pr-bodies.cjs');

// ---------------------------------------------------------------------------
// inferWorkflowFromBranch
// ---------------------------------------------------------------------------
test('inferWorkflowFromBranch detects audit-auto-prs', () => {
  assert.equal(
    inferWorkflowFromBranch(
      'claude-workflow-optimize-auto-pr-audit-12345',
    ),
    'audit-auto-prs',
  );
});

test('inferWorkflowFromBranch detects fix-issue', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-fix-issue-949-20260729-0500'),
    'fix-issue',
  );
});

test('inferWorkflowFromBranch detects suggest-improvements', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-suggest-12345'),
    'suggest-improvements',
  );
});

test('inferWorkflowFromBranch detects docs-drift', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-docs-drift-67890'),
    'docs-drift',
  );
});

test('inferWorkflowFromBranch detects monitor', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-monitor-11111'),
    'monitor-amnezia-control-panel-github-runs',
  );
});

test('inferWorkflowFromBranch detects maintenance', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-health-22222'),
    'maintenance',
  );
});

test('inferWorkflowFromBranch detects workflow-health-optimize', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-workflow-health-33333'),
    'workflow-health-optimize',
  );
});

test('inferWorkflowFromBranch detects gsd-planning', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-gsd-planning-44444'),
    'gsd-planning',
  );
});

test('inferWorkflowFromBranch detects gsd-planning-execute', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-gsd-exec-55555'),
    'gsd-planning-execute',
  );
});

test('inferWorkflowFromBranch defaults to claude-automation', () => {
  assert.equal(
    inferWorkflowFromBranch('claude-other-branch'),
    'claude-automation',
  );
});

test('inferWorkflowFromBranch handles claude/ prefix', () => {
  assert.equal(
    inferWorkflowFromBranch('claude/some-feature'),
    'claude-automation',
  );
});

test('inferWorkflowFromBranch handles codex/ prefix', () => {
  assert.equal(
    inferWorkflowFromBranch('codex/fix-something'),
    'codex-automation',
  );
});

test('inferWorkflowFromBranch returns unknown for non-automation', () => {
  assert.equal(inferWorkflowFromBranch('main'), 'unknown');
  assert.equal(inferWorkflowFromBranch('feature/foo'), 'unknown');
});

// ---------------------------------------------------------------------------
// lintPrBody
// ---------------------------------------------------------------------------
test('lintPrBody passes for complete body', () => {
  const body = [
    '## Problem / Trigger',
    'x',
    '## Why Automation Changed This',
    'x',
    '## What Changed',
    'x',
    '## Evidence',
    'x',
    '## Review Notes',
    'x',
    '---',
    '*Auto-generated by test.*',
  ].join('\n');
  const result = lintPrBody(body);
  assert.deepEqual(result.missing, []);
  assert.equal(result.hasFooter, true);
});

test('lintPrBody detects missing sections', () => {
  const body = '## Problem / Trigger\nx\n## Review Notes\ny\n';
  const result = lintPrBody(body);
  assert.ok(result.missing.length > 0);
  assert.ok(result.missing.includes('## Why Automation Changed This'));
});

test('lintPrBody detects missing footer', () => {
  const body = [
    '## Problem / Trigger', 'x', '## Why Automation Changed This', 'x',
    '## What Changed', 'x', '## Evidence', 'x', '## Review Notes', 'x',
  ].join('\n');
  const result = lintPrBody(body);
  assert.equal(result.hasFooter, false);
});

test('lintPrBody handles empty body', () => {
  const result = lintPrBody('');
  assert.equal(result.missing.length, 5);
  assert.equal(result.hasFooter, false);
});

test('lintPrBody handles null body', () => {
  const result = lintPrBody(null);
  assert.ok(result.missing.length > 0);
  assert.equal(result.hasFooter, false);
});

test('lintPrBody requires headings as exact full lines', () => {
  // "## What Changed" appears only inside a longer heading and inside prose,
  // never as a standalone line. An unanchored substring match would wrongly
  // pass; the anchored check must still flag it as missing.
  const body = [
    '## Problem / Trigger', 'x', '## Why Automation Changed This', 'x',
    '## What Changed in v2', 'we discuss what ## What Changed means here',
    '## Evidence', 'x', '## Review Notes', 'x',
    '---', '*Auto-generated by test.*',
  ].join('\n');
  const result = lintPrBody(body);
  assert.ok(
    result.missing.includes('## What Changed'),
    'expected ## What Changed to be flagged missing when not a full line',
  );
});

test('lintPrBody matches headings that are exact full lines', () => {
  const body = [
    '## Problem / Trigger', 'x', '## Why Automation Changed This', 'x',
    '## What Changed', 'x', '## Evidence', 'x', '## Review Notes', 'x',
    '---', '*Auto-generated by test.*',
  ].join('\n');
  const result = lintPrBody(body);
  assert.deepEqual(result.missing, []);
});

// ---------------------------------------------------------------------------
// lintAutomationPrs (pure data-path, no I/O)
// ---------------------------------------------------------------------------
test('lintAutomationPrs skips non-automation PRs', () => {
  const prs = [
    { number: 1, title: 'Manual PR', headRefName: 'feature/foo', author: { login: 'human' } },
  ];
  const result = lintAutomationPrs(prs, () => 'full body with all sections');
  assert.equal(result.inspected, 0);
  assert.equal(result.offenders.length, 0);
});

test('lintAutomationPrs passes clean automation PRs', () => {
  const prs = [
    {
      number: 10,
      title: 'ci: fix',
      headRefName: 'claude-fix-issue-123',
      author: { login: 'claude[bot]' },
    },
  ];
  const fullBody = [
    '## Problem / Trigger', 'x', '## Why Automation Changed This', 'x',
    '## What Changed', 'x', '## Evidence', 'x', '## Review Notes', 'x',
    '---', '*Auto-generated by fix-issue.*',
  ].join('\n');
  const result = lintAutomationPrs(prs, () => fullBody);
  assert.equal(result.inspected, 1);
  assert.equal(result.offenders.length, 0);
});

test('lintAutomationPrs detects PRs with missing sections', () => {
  const prs = [
    {
      number: 20,
      title: 'ci: audit',
      headRefName: 'claude-workflow-optimize-auto-pr-audit-999',
      author: { login: 'claude[bot]' },
    },
  ];
  const badBody = 'Some minimal body without sections';
  const result = lintAutomationPrs(prs, () => badBody);
  assert.equal(result.inspected, 1);
  assert.equal(result.offenders.length, 1);
  assert.equal(result.offenders[0].number, 20);
  assert.equal(result.offenders[0].workflow, 'audit-auto-prs');
  assert.ok(result.offenders[0].issues.length > 0);
  assert.ok(result.byWorkflow['audit-auto-prs']);
});

test('lintAutomationPrs groups offenders by workflow', () => {
  const prs = [
    {
      number: 30,
      title: 'ci: fix A',
      headRefName: 'claude-fix-issue-100',
      author: { login: 'claude[bot]' },
    },
    {
      number: 31,
      title: 'ci: fix B',
      headRefName: 'claude-fix-issue-200',
      author: { login: 'claude[bot]' },
    },
    {
      number: 32,
      title: 'ci: suggest',
      headRefName: 'claude-suggest-300',
      author: { login: 'claude[bot]' },
    },
  ];
  const badBody = 'minimal';
  const result = lintAutomationPrs(prs, () => badBody);
  assert.equal(result.offenders.length, 3);
  assert.equal(result.byWorkflow['fix-issue'].length, 2);
  assert.equal(result.byWorkflow['suggest-improvements'].length, 1);
});

test('lintAutomationPrs handles empty PR list', () => {
  const result = lintAutomationPrs([], () => '');
  assert.equal(result.inspected, 0);
  assert.equal(result.offenders.length, 0);
});

test('lintAutomationPrs handles null/undefined PR entries', () => {
  const prs = [null, undefined, { number: 40, headRefName: 'claude-fix-1' }];
  const fullBody = [
    '## Problem / Trigger', 'x', '## Why Automation Changed This', 'x',
    '## What Changed', 'x', '## Evidence', 'x', '## Review Notes', 'x',
    '---', '*Auto-generated by fix-issue.*',
  ].join('\n');
  const result = lintAutomationPrs(prs, () => fullBody);
  assert.equal(result.inspected, 1);
  assert.equal(result.offenders.length, 0);
});

// ---------------------------------------------------------------------------
// AUTOMATION_BRANCH_PREFIXES constant
// ---------------------------------------------------------------------------
test('AUTOMATION_BRANCH_PREFIXES contains expected prefixes', () => {
  assert.ok(AUTOMATION_BRANCH_PREFIXES.includes('claude-'));
  assert.ok(AUTOMATION_BRANCH_PREFIXES.includes('claude/'));
  assert.ok(AUTOMATION_BRANCH_PREFIXES.includes('codex/'));
});
